<?php
/**
 * Display 500 error message.
 */
use function pirogue\dispatcher_create_url;
use function pirogue\database_collection_get;
use function pirogue\error_handler_log;

http_response_code(500);
error_handler_log(database_collection_get(), $GLOBALS['.pirogue.view.data']['exception']->getMessage(), $GLOBALS['.pirogue.view.data']['exception']->getFile(), $GLOBALS['.pirogue.view.data']['exception']->getLine());

?>
<div class="">
	<p>Request: <?php echo dispatcher_create_url( $GLOBALS['.pirogue.view.data']['path'], $GLOBALS['.pirogue.view.data']['data']); ?></p>
	<pre><?php echo $GLOBALS['.pirogue.view.data']['exception']->getMessage(); ?></pre>
	<pre><?php printf('%s (%d)', $GLOBALS['.pirogue.view.data']['exception']->getFile(), $GLOBALS['.pirogue.view.data']['exception']->getLine()); ?></pre>
</div>

