<?php

// define constants

// Use functions
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\dispatcher_redirect;
use function pirogue\dispatcher_create_url;

// Import libraries
import('pirogue\dispatcher');
import('pirogue\database_collection');

/**
 * Prompt user for email and verify in database.
 */

// Initialize page variables
$_SESSION['.auth.login']['user_data'] = null;
$_SESSION['.auth.login']['start'] = false;

unset($_SESSION['.auth.login.site_user']);
$_email = $GLOBALS['.pirogue.view.data']['email'] ?? '';
$_errors = [];

// Process post request using post id data
if ('POST' == $_SERVER['REQUEST_METHOD'] && 'lookup' == ($_POST['action'] ?? '')) {
    $_email = trim($_POST['email'] ?? '');
    if ('' == trim($_email)) {
        $_errors['email'] = 'Email is required.';
    } else {
        $_database = database_collection_get('example-site');
        $_sql_statement = sqlsrv_query($_database, 'select id, email_address, status_code, display_name, position_name, location_name, department_name from site.user_details where email_address=?', [
            $_email
        ]);
        $_sql_data = (null == $_sql_statement) ? null : sqlsrv_fetch_array($_sql_statement, SQLSRV_FETCH_ASSOC);
        sqlsrv_free_stmt($_sql_statement);

        if (null == $_sql_data) {
            $_errors['email'] = 'Unable to find requested account.';
        } elseif (SITE_USER_ACTIVE != (SITE_USER_ACTIVE & $_sql_data['status_code'])) {
            $_errors['email'] = 'Account not active.';
        } else {
            // save user and move to next step
            $_SESSION['.auth.login']['user_data'] = $_sql_data;
            dispatcher_redirect();
        }
    }
}

$GLOBALS['.pirogue.view.body.id'] = 'auth-lookup';
$GLOBALS['.pirogue.view.body.class'] = '';

array_push($GLOBALS['.pirogue.view.script.files'], 'form');
array_push($GLOBALS['.pirogue.view.script.files'], 'page');
?>
<form id="" action="<?php echo dispatcher_create_url(); ?>"
	method="post" class="" autocomplete="off">
	<input type="hidden" name="" value="" />
	<div class="">
		<div class="">
			<label for="inputEmail">Email Address</label> <input id="inputEmail" class="onload-focus"
				type="text" value="<?php echo $_email; ?>" name="email" />
		</div>
    	<?php if ( array_key_exists('email', $_errors) ): ?>
    		<p class=""><?php echo $_errors['email']; ?></p>
    	<?php endif; ?>
	</div>
	<div class="">
		<a
			href="<?php echo dispatcher_create_url('reset', $GLOBALS['.pirogue.dispatcher.request_data']); ?>"
			class=""> <span class="">Cancel login</span>
		</a> <input type="submit" value="lookup" name="action" />
	</div>
</form>