<?php

// Use functions
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\dispatcher_redirect;
use function pirogue\dispatcher_create_url;

// Import libraries
import('pirogue\dispatcher');
import('pirogue\database_collection');

/**
 * Prompt user for password and verify in database.
 */

// Initialize page variables
$_errors = [];
$_site_user = $_SESSION['.auth.login.site_user'] ?? null;

// Process post request using post id data
if ('POST' == $_SERVER['REQUEST_METHOD'] && 'login' == ($_POST['action'] ?? '')) {
    $_site_user_id = $_site_user['id'];
    $_password = trim($_POST['password'] ?? '');
    if ('' == trim($_password)) {
        $_errors['password'] = 'Password is required.';
    } else {
        $_database = database_collection_get('example-site');
        $_sql_statement = sqlsrv_query($_database, 'select match_count=COUNT(id) from site.users where password=site.password_encrypt(?) and id=?', [
            $_password,
            $_site_user_id
        ]);
        $_sql_data = (null == $_sql_statement) ? null : sqlsrv_fetch_array($_sql_statement, SQLSRV_FETCH_ASSOC);
        sqlsrv_free_stmt($_sql_statement);

        if (null == $_sql_data) {
            $_errors['password'] = 'Error occurred.';
        } elseif (0 == $_sql_data['match_count']) {
            $_errors['password'] = 'Invalid password.';
        } else {
            // start session
            // session_start($_site_user);
            exit('start session');            

            // redirect user to initial request or landing page 
            dispatcher_redirect();
        }
    }
}

?>
<form id="" action="<?php echo dispatcher_create_url(); ?>"
	method="post" class="">
	<input type="hidden" name="" value="" />
	<div class="">
		<div class="">
			<?php echo $_site_user['email']; ?>
		</div>
		<div class="">
			<label for="inputPassword">Password</label> <input id="inputPassword"
				type="password" value="" name="password" />
		</div>
    	<?php if ( array_key_exists('password', $_errors) ): ?>
    		<p class=""><?php echo $_errors['password']; ?></p>
    	<?php endif; ?>
	</div>
	<div class="">
		<input type="submit" value="login" name="action" />
	</div>
</form>