<?php

// define constants
define('SITE_USER_ACTIVE', 0x01);

// Use functions
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\dispatcher_redirect;
use function pirogue\dispatcher_create_url;

if (! ($_SESSION['.auth.login.terms'] ?? false)) {
    return include ('_disclaimer.phtml');
} elseif (null !== ($_SESSION['.auth.login.site_user'] ?? null)) {
    return include ('_password.phtml');
} else {
    return include ('_lookup.phtml');
}