<?php

?>
<table id="varList">
    <colgroup style="width: 25ex;"/>
    <colgroup style="width: 25ex;"/>
    <colgroup>
    <tr><th>._dispatcher_path</th><td colspan="2"><?php echo implode( '/', $GLOBALS['._dispatcher_path']); ?></td></tr>
    <tr><th>._dispatcher_view</th><td colspan="2"><?php echo $GLOBALS['._dispatcher_view'] ?? ''; ?></td></tr>
    <tr><th>.request_path</th><td colspan="2"><?php echo implode( '/', $GLOBALS['.request_path']); ?></td></tr>
    <tr><th>.request_module</th><td colspan="2"><?php echo $GLOBALS['.request_module']; ?></td></tr>
    <tr><th>.request_page</th><td colspan="2"><?php echo $GLOBALS['.request_page']; ?></td></tr>
    <tr>
        <th>.request_data</th>
        <td>
            <?php $_request_data = array_keys($GLOBALS['.request_data']); ?>
            <?php $_key = array_shift($_request_data); ?>
            <?php echo $_key ?? '&nbsp;'; ?>
        </td>
        <td><?php echo $GLOBALS['.request_data'][$_key] ?? '&nbsp;'; ?></td>
    </tr>
    <?php foreach ( $_request_data as $_key ): ?>
        <tr>
            <th>&nbsp;</th>
            <td><?php echo $_key; ?></td>
            <td><?php echo $GLOBALS['.request_data'][$_key] ?? '&nbsp;'; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php ob_start(); ?>
    <style>
        #varList{ width: 100%;}
        #varList td, #varList th{ text-align: left; padding: .25ex 1ex; line-height: 150%;}
    </style>
<?php $GLOBALS['.html.css.inline'] = ob_get_clean();