<?php
    

?>
<table id="varList">
    <?php foreach ( $GLOBALS as $_key => $_value ): ?>
        <?php if ( preg_match('/pirogue/', $_key) ): ?>
            <tr>
                <th><?php echo $_key; ?></th>
                <td>
                    <?php if ( is_array($_value) ): ?>
                        <pre><?php print_r($_value); ?></pre>
                    <?php elseif ( is_object($_value) ): ?>
                        <pre><?php print_r($_value); ?></pre>
                    <?php else: ?>
                        <?php echo $_value; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
</table>
<?php ob_start(); ?>
    <style>
        #varList td, #varList th{ text-align: left; padding: .25ex 1ex; line-height: 150%;}
    </style>
<?php $GLOBALS['.html.css.inline'] = ob_get_clean();
