<?php

    $_form_errors = [];
    
    if ( 'POST' == $_SERVER['REQUEST_METHOD'] && 'redirect' == $_POST['action'] ?? '' ){
        $_form_errors['redirect-uri'] = match (intval($_POST['redirect-uri'] ?? '')){
            0 => 'Redirect option required.',
            1 => pirogue_dispatcher_redirect(),
            2 => pirogue_dispatcher_redirect(pirogue_dispatcher_create_url($GLOBALS['.request_module'], [])),
            3 => pirogue_dispatcher_redirect(pirogue_dispatcher_create_url('', [])),
            4 => pirogue_dispatcher_redirect(pirogue_dispatcher_create_url('invalid-path', [])),                
            default => 'Invalid option.',
        };
    }

    // Build page.
    site_html_create(html_title: 'Test Redirect', page_title: 'Test Redirect');

?>
<form id="" method="POST" action="<?php echo pirogue_dispatcher_create_url($GLOBALS['.pirogue.dispatcher.request_path'], $GLOBALS['.pirogue.dispatcher.request_data']); ?>">
    <?php if ( array_key_exists('form', $_form_errors) ): ?>
        <p class="error-mesasage"><?php echo $_form_errors['form']; ?></p>
    <?php endif; ?>
    <div class="form-entry <?php echo array_key_exists('redirect-uri', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <select id="" name="redirect-uri">
            <option value=""> -- Select URI</option>
            <option value="1">Refresh Redirect</option>
            <option value="2">Module Index</option>
            <option value="3">Main landing page</option>
            <option value="4">Invalid Redirect (404)</option>
        </select>
        <?php if ( array_key_exists('redirect-uri', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['redirect-uri']; ?></p>
        <?php endif; ?>
    </div>
    <div class="">
        <button name="action" type="submit" value="redirect"><span class="">Redirect</span></button>
    </div>
</form>