<?php

    $_form_errors = [];
    
    if ('POST' == $_SERVER['REQUEST_METHOD']){
        if ('cancel' == $_POST['action'] ?? '') {
            return pirogue_dispatcher_redirect(pirogue_dispatcher_create_url($GLOBALS['.request_module'], []));
        } elseif ('create' == $_POST['action'] ?? ''){
            // get user input.
            $_notice_text = trim($_POST['notice-text'] ?? '');
            $_notice_type = match (trim($_POST['notice-type'] ?? '')){
                'warning' => 'warning',
                'error' => 'error',
                'info' => 'info',
                default => ''
            };

            // validate input.
            if ('' == $_notice_text) {
                $_form_errors['notice-text']  = 'Message required.';
            }            

            if ('' == $_notice_type) {
                $_form_errors['notice-type']  = 'Invalid message type.';
            }

            // process input.
            if (empty($_form_errors)) {
                pirogue_site_notices_create($_notice_type, $_notice_text);
                return pirogue_dispatcher_redirect(pirogue_dispatcher_create_url($GLOBALS['.request_module'], []));
            } else {
                $_form_errors['form']  = 'Unable to save messge.';
            }
        }
    }

    // Build page.
    site_html_create(html_title: 'Test Site Notices', page_title: 'Test Site Notices');

?>
<div class="page-actions">
    <a class="link-back" href="<?php echo pirogue_dispatcher_create_url($GLOBALS['.request_module'], []); ?>"><span class="">Back to list</span></a>
</div>
<form class="form" id="" method="POST" action="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s.html', $GLOBALS['.request_module'], $GLOBALS['.request_page']), []); ?>">
    <?php if ( array_key_exists('form', $_form_errors) ): ?>
        <p class="error-mesasage"><?php echo $_form_errors['form']; ?></p>
    <?php endif; ?>
    <div class="form-entry <?php echo array_key_exists('notice-type', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <label class="form-entry-label" for="">Notice Type</label>
        <select class="form-entry-content form-entry-input" id="" name="notice-type">
            <option value="warning">Warning</option>
            <option value="error">Error</option>
            <option value="info">Information</option>
        </select>
        <?php if ( array_key_exists('notice-type', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['notice-type']; ?></p>
        <?php endif; ?>
    </div>
    <div class="form-entry form-entry-required <?php echo array_key_exists('notice-text', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <label class="form-entry-label" for="">Notice Text</label>
        <input class="form-entry-content form-entry-input" type="text" placeholder="Message text." name="notice-text" value="" />
        <?php if ( array_key_exists('notice-text', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['notice-text']; ?></p>
        <?php endif; ?>
    </div>
    
    <div class="form-entry form-entry-controls">
        <button name="action" type="submit" value="cancel"><span class="">Cancel</span></button>
        <button name="action" type="submit" value="create"><span class="">Test messages</span></button>
    </div>
</form>