<?php

    $_form_errors = [];
    
    if ( 'POST' == $_SERVER['REQUEST_METHOD'] ){
        if ( 'test' == $_POST['action'] ?? '' ){
            $_label = trim($_POST['label'] ?? '');
            if ( '' == $_label ) {
                $_form_errors['label']  = 'Label required.';
            }

            if ( empty($_form_errors) ) {
                pirogue_user_session_set($_label, trim($_POST['value'] ?? ''));
                return pirogue_dispatcher_redirect();
            }
        } elseif ( 'delete' == $_POST['action'] ?? '' ) {
            $_label = trim($_POST['delete-label']??'');
                pirogue_user_session_remove($_label);
                return pirogue_dispatcher_redirect();
        }
    }

    // Build page.
    site_html_create(html_title: 'User Session', page_title: 'User Session');

?>
<form id="" method="POST" action="<?php echo pirogue_dispatcher_create_url($GLOBALS['.pirogue.dispatcher.request_path'], $GLOBALS['.pirogue.dispatcher.request_data']); ?>">
    <?php if ( array_key_exists('form', $_form_errors) ): ?>
        <p class="error-mesasage"><?php echo $_form_errors['form']; ?></p>
    <?php endif; ?>
    <div class="form-entry <?php echo array_key_exists('label', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <input type="text" placeholder="Variable label." name="label" value="" />
        <input type="text" placeholder="Variable value." name="value" value="" />
        <?php if ( array_key_exists('label', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['label']; ?></p>
        <?php endif; ?>
    </div>
    <div class="">
        <button name="action" type="submit" value="test"><span class="">Save Variable</span></button>
    </div>
</form>
<div id="">    
    <?php if ( !empty($_SESSION[$GLOBALS['._pirogue.user_session.label_data']]) ): ?>
        <?php foreach ( $_SESSION[$GLOBALS['._pirogue.user_session.label_data']] as $_label => $_value ): ?>
            <form id="" method="POST" action="<?php echo pirogue_dispatcher_create_url($GLOBALS['.pirogue.dispatcher.request_path'], $GLOBALS['.pirogue.dispatcher.request_data']); ?>">
                <input type="hidden" value="<?php echo $_label; ?>" name="delete-label">
                <label class=""><?php echo $_label; ?></label>
                <span class=""><?php echo $_value; ?></span>
                <button name="action" type="submit" value="delete"><span class="">Delete</span></button>
            </form>
        <?php endforeach; ?>
    <?php endif; ?>
    <form id="" method="POST" action="<?php echo pirogue_dispatcher_create_url($GLOBALS['.pirogue.dispatcher.request_path'], $GLOBALS['.pirogue.dispatcher.request_data']); ?>">
        <input type="hidden" value="no such" name="delete-label">
        <label class="">[INVALID VARIABLE]</label>
        <span class="">[INVALID VARIABLE VALUE]</span>
        <button name="action" type="submit" value="delete"><span class="">Delete</span></button>
    </form>
</div>
