<?php
use function pirogue\dispatcher_create_url;

$_user_session = user_session_current();
$_sqlsrv = database_collection_get();
site_user_require_access($_sqlsrv, $_user_session['id'], $GLOBALS['.pirogue.request.application']);

?>
<?php foreach( scandir(sprintf('%s\_list', __DIR__)) as $_file): ?>
	<?php if ( false == is_dir($_file) ): ?>
		<a href="<?php echo dispatcher_create_url("{$GLOBALS['.pirogue.request.application']}/test/{$_file}"); ?>" class="" id="">
			<span class=""><?php echo $_file; ?></span>
		</a>
	<?php endif; ?>
<?php endforeach; ?>

