<?php

  
    array_push($GLOBALS['.pirogue.view.script.files'], 'xhr');

?>
<p id="getXhr"></p>
<p id="postXhr"></p>
<?php ob_start(); ?>

<script>

xhr_get("site-test/get.json")
	.then(x => document.getElementById('getXhr').innerHTML = x)
	.catch(x => document.getElementById('getXhr').innerHTML = x);


xhr_post("site-test/post/1.json?and=this", {'id':1, 'name': 'yes'})
	.then(x => document.getElementById('postXhr').innerHTML = x)
	.catch(x => document.getElementById('postXhr').innerHTML = x);

</script>
<?php $GLOBALS['.pirogue.view.script.inline'] = ob_get_clean(); ?>