FROM php:8.0-alpine
LABEL maintainer="sean bourg <sean.bourg@gmail.com>"

COPY entrypoint.sh /entrypoint.sh
COPY run.sh /run.sh

RUN chmod +x /entrypoint.sh; \
    chmod +x /run.sh; \
    mkdir /var/pirogue-testing; \ 
    docker-php-ext-install mysqli;

COPY phpcs.xml /var/pirogue-testing/phpcs.xml

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/run.sh"]
