version: '3'
services:
    web:
        image: nginx:alpine
        container_name: pirogue-http
        env_file: .env/development
        volumes:
            - ./volumes/etc/web/default.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./volumes/var/log/nginx:/var/log/nginx:rw
            - ./volumes/etc/ssl:/app/ssl:ro
            - ./volumes/app/www:/app/www:ro
        networks:
            - app-network
            - app-internal
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
            - php
        links: 
            - php
    php:
        build:
            context: ./build
            dockerfile: php
        env_file: .env/development
        depends_on: 
            - database
        links: 
            - database
        volumes:
            - ./volumes/etc/php/config.ini:/usr/local/etc/php/conf.d/config.ini:ro
            - ./volumes/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./volumes/etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./volumes/app/www:/app/www:ro
            - ./volumes/app/include:/app/include:ro
            - ./volumes/app/config:/app/config:ro
            - ./volumes/var/log/php-fpm:/usr/local/var/log/:rw
        networks: 
            - app-internal
        restart: always
        depends_on:
            - database
        links:
            - database

    database:
        image: mariadb:10.4
        container_name: pirogue-database
        env_file: .env/development
        volumes:
            - ./volumes/database/initdb.d:/docker-entrypoint-initdb.d:ro
            - ./volumes/database/data:/var/lib/mysql:rw
        networks: 
            - app-internal
        ports:
            - 3306:3306
        restart: always

    siege:
        build:
            context: ./build
            dockerfile: siege
        container_name: pirogue-siege
        env_file: .env/development
        stdin_open: true
        tty: true
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge
        internal: false

    app-internal:
        driver: bridge
        internal: true
    