<?php
use function pirogue\database_collection_get;
use function pirogue\dispatcher_create_url;
use function pirogue\user_session_current;
use function site_access\site_access_fetch;

if (false === array_search('admin', $GLOBALS['.pirogue.site_access.roles'])) {
    $GLOBALS['.pirogue.site_access.has_access'] = false;
    return;
}


// Base data (site_access).
$GLOBALS['.pirogue.site_access.has_access'];
$GLOBALS['.pirogue.site_access.application'];
$GLOBALS['.pirogue.site_access.roles'];


// Base data (request).
$GLOBALS['.pirogue.request.data'];
$GLOBALS['.pirogue.request.application'];
$GLOBALS['.pirogue.request.path'];

// Base data (html).
$GLOBALS['.pirogue.html.body.menu_file'];
$GLOBALS['.pirogue.html.head'];
$GLOBALS['.pirogue.html.head.title'];
$GLOBALS['.pirogue.html.body.id'];
$GLOBALS['.pirogue.html.body.class'];
$GLOBALS['.pirogue.html.css.files'];
$GLOBALS['.pirogue.html.css.inline'];
$GLOBALS['.pirogue.html.script.inline'];
$GLOBALS['.pirogue.html.script.files'];


$_sql_filter = [];
$_sql_query = 'select id, employee_number, name=dbo.name_format(name_surname, name_given, name_middle, name_generation_qualifier, name_title), email_address, [status]
	from org.employee_details';


$_sql_query = ( 0 == count($_sql_filter)) ? $_sql_query : sprintf('%s where %s', $_sql_query, implode(' and ', $_sql_filter));
$_sql_order_field = 'id';
$_sql_order_dir = 'asc';
echo "{$_sql_query} order by {$_sql_order_field} {$_sql_order_dir}";