<?php

// Use functions
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\dispatcher_redirect;
use function pirogue\dispatcher_create_url;

// Import libraries
import('pirogue\dispatcher');
import('pirogue\database_collection');

/**
 * Prompt user for password and verify in database.
 */

// Initialize page variables
$_errors = [];
$_site_user = $_SESSION['.auth.login']['user_data'];
$_SESSION['.auth.login']['start'] = false;

// Process post request using post id data
if ('POST' == $_SERVER['REQUEST_METHOD'] && 'login' == ($_POST['action'] ?? '')) {
    $_site_user_id = $_site_user['id'];
    $_password = trim($_POST['password'] ?? '');
    if ('' == trim($_password)) {
        $_errors['password'] = 'Password is required.';
    } else {
        $_database = database_collection_get('example-site');
        $_sql_statement = sqlsrv_query($_database, 'select match_count=COUNT(id) from site.users where password=site.password_encrypt(?) and id=?', [
            $_password,
            $_site_user_id
        ]);
        $_sql_data = (null == $_sql_statement) ? null : sqlsrv_fetch_array($_sql_statement, SQLSRV_FETCH_ASSOC);
        sqlsrv_free_stmt($_sql_statement);

        if (null == $_sql_data) {
            $_errors['password'] = 'Error occurred.';
        } elseif (0 == $_sql_data['match_count']) {
            $_errors['password'] = 'Invalid password.';
        } else {
            $_SESSION['.auth.login']['start'] = true;
            return dispatcher_redirect();
        }
    }
}

$GLOBALS['.pirogue.html.body.id'] = 'login';
$GLOBALS['.pirogue.html.body.class'] = 'password';
$GLOBALS['.pirogue.html.script.files'] = array_merge($GLOBALS['.pirogue.html.script.files'], [
    'form',
    'page'
]);

?>
<form id="" action="<?php echo dispatcher_create_url(); ?>"
	method="post" class="" autocomplete="off">
	<input type="hidden" name="" value="" />
	<div class="">
		<div class="">
			<p><?php echo $_site_user['display_name']; ?></p>
			<?php if ( !empty($_site_user['position_name']) ): ?>
				<p><?php echo $_site_user['position_name']; ?></p>
			<p><?php echo $_site_user['location_name'], ' - ', $_site_user['department_name']; ?></p>
			<?php endif; ?>
		</div>
		<div class="">
			<a
				href="<?php echo dispatcher_create_url('login', $GLOBALS['.pirogue.dispatcher.request_data']); ?>"
				class="fas fas-arrow-left"> <span class="">Not my account</span>
			</a>
		</div>
		<div class="">
			<label for="inputPassword">Password</label> <input id="inputPassword"
				class="onload-focus" type="password" value="" name="password" />
		</div>
    	<?php if ( array_key_exists('password', $_errors) ): ?>
    		<p class=""><?php echo $_errors['password']; ?></p>
    	<?php endif; ?>
	</div>
	<div class="">
		<a
			href="<?php echo dispatcher_create_url('reset', $GLOBALS['.pirogue.dispatcher.request_data']); ?>"
			class="fas fa-times"> <span class="">Cancel login</span>
		</a>
		<button type="submit" value="login" name="action"
			class="fas fa-sign-in-alt">
			<span class="">Login</span>
		</button>

	</div>
</form>