<?php

// define constants
define('SITE_USER_ACTIVE', 0x01);

// Use functions
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\dispatcher_redirect;
use function pirogue\dispatcher_create_url;
use function pirogue\_user_session_start;

import('pirogue\user_session');

// look for action first:

if (false == array_key_exists('.auth.login', $_SESSION)) {
    $_SESSION['.auth.login'] = [
        'terms' => false,
        'user_data' => null,
        'start' => false
    ];
}

if (false == $_SESSION['.auth.login']['terms']) {
    include ('_disclaimer.phtml');
} elseif (true == $_SESSION['.auth.login']['start']) {
    // start session
    _user_session_start($_SESSION['.auth.login']['user_data']);
    unset($_SESSION['.auth.login']);

    // build redirect request
    $_request_data = $GLOBALS['.pirogue.view.data'];
    $_path = $_request_data['redirect_path'] ?? 'index';
    unset($_request_data['redirect_path']);

    // redirect to main site
    return dispatcher_redirect(dispatcher_create_url("../{$_path}", $_request_data));
} elseif (null !== $_SESSION['.auth.login']['user_data']) {
    include ('_password.phtml');
} else {
    include ('_lookup.phtml');
}

