<?php

    $_menu = require implode(DIRECTORY_SEPARATOR, [__DIR__, '_menu.php']) ?? [];

?>
<?php if ( empty($_menu) ): ?>
<?php else: ?>
    <?php foreach ( $_menu as $_entry ): ?>
        <li>
            <a href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s', $GLOBALS['.request_module'], $_entry['path'] ?? ''), $_entry['request'] ?? []); ?>" title="<?php echo $_entry['title'] ?? ''; ?>">
                <span class=""><?php echo $_entry['label'] ?? 'Menu Option'; ?><span>
            </a>
        </li>    
    <?php endforeach; ?>
<?php endif; ?>
