<?php

/**
 * 
 */


$_application_url = $GLOBALS['.pirogue.dispatcher.address'];
$_application_title = empty($GLOBALS['.html.body.title']) ? 'Example Site' : $GLOBALS['.html.body.title'];
$GLOBALS['.pirogue.dispatcher.address'] = '';

?>
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <title><?php echo $GLOBALS['.html.head.title'] ?? $_application_title; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
        	@font-face {
                	font-family: "Font Awesome 5 Brands";
                	font-style: normal;
                	font-weight: normal;
                	font-display: auto;
                	src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.eot);
                	src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.eot?#iefix)
                		format("embedded-opentype"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.woff2)
                		format("woff2"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.woff) format("woff"),
                		url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.ttf) format("truetype"),
                		url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-brands-400.svg#fontawesome) format("svg")
            }
            @font-face {
                font-family: "Font Awesome 5 Free";
                font-style: normal;
                font-weight: 400;
                font-display: auto;
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.eot);
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.eot?#iefix)
                	format("embedded-opentype"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.woff2)
                	format("woff2"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.woff) format("woff"),
                	url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.ttf) format("truetype"),
                	url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-regular-400.svg#fontawesome) format("svg")
            }
            @font-face {
                font-family: "Font Awesome 5 Free";
                font-style: normal;
                font-weight: 900;
                font-display: auto;
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.eot);
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.eot?#iefix)
                	format("embedded-opentype"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.woff2)
                	format("woff2"), url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.woff) format("woff"),
                	url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.ttf) format("truetype"),
                	url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/font-awesome/fa-solid-900.svg#fontawesome) format("svg")
            }
            @font-face {
                font-family: "Roboto";
                font-style: normal;
                font-weight: normal;
                font-display: auto;
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/roboto/Roboto-Regular.ttf) format("truetype");
            }                
            @font-face {
                font-family: "Roboto Slab";
                font-style: normal;
                font-weight: normal;
                font-display: auto;
                src: url(<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/webfonts/roboto-slab/RobotoSlab-Regular.ttf) format("truetype");
            }        
        </style>
        <link rel="manifest" href="site.webmanifest">
        <link rel="stylesheet" href="<?php echo $GLOBALS['.pirogue.dispatcher.address'] ?? ''; ?>/assets/style/normalize.css">
        <link rel="stylesheet" href="<?php echo $GLOBALS['.pirogue.dispatcher.address'] ?? ''; ?>/assets/style/base.css">
		<?php foreach( array_unique($GLOBALS['.html.css.files'] ?? []) as $_file ): ?>
      		<link rel="stylesheet" href="<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/style/<?php echo $_file; ?>.css" />
      	<?php endforeach; ?>
      	<?php echo $GLOBALS['.html.css.inline'] ?? '' ?>
      	<meta name="theme-color" content="#fafafa">
      	<?php echo $GLOBALS['.html.head'] ?? ''; ?>
	</head>
	<body id="<?php echo $GLOBALS['.html.body.id'] ?? '' ?>" class="<?php echo $GLOBALS['.html.body.class'] ?? '' ?>">
		<nav id="page-menubar">
    		<div id="page-application" class="">
    			<h1 id="page-application-title" class="">
    				<a id="" class="" href="<?php echo $_application_url; ?>">
    					<span class=""><?php echo $_application_title; ?></span>
    				</a>
    			</h1>
    		</div>
    	</nav>
    	<div class="" id="page-content"><?php echo $GLOBALS['.html.body.content'] ?? '' ?></div>
    	<?php $_files = array_unique($GLOBALS['.html.script.files'] ?? []);?>
        <?php foreach( $_files as $_file ): ?>
        	<script src="<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>/assets/script/<?php echo $_file; ?>.js"></script>
        <?php endforeach; ?>
    	<?php echo $GLOBALS['.html.script.inline'] ?? '' ?>
	</body>
</html>
