<?php

    use function pirogue\dispatcher_redirect;
    use function pirogue\dispatcher_create_url;

    $GLOBALS['.html.head.title'] = 'Testing Dispatcher';
    $GLOBALS['.html.css.files'] = [];
    $GLOBALS['.html.script.files'] = [];
    $GLOBALS['.html.body.class'] = '';
    $GLOBALS['.html.body.id'] = 'testing-dispatcher';


    $_form_errors = [];

    if ( true == array_key_exists('redirect-path', $GLOBALS['.request_data'])){
        $_path = trim($GLOBALS['.request_data']['redirect-path']);
        if ( empty($_path) ){
            $_form_errors['request-path'] = 'request path not specified';
        }
        
        if ( 0 == count($_form_errors) ) {
            return dispatcher_redirect(
                dispatcher_create_url($_path, []), 
                intval($GLOBALS['.request_data']['redirect-code'] ?? 301) 
            );
        }
    }
?>

<?php ob_start(); ?>    
<?php $GLOBALS['.html.head'] = ob_get_clean(); ?>
    
<?php ob_start(); ?>    
    <style>
    </style>
<?php $GLOBALS['.html.css.inline'] = ob_get_clean(); ?>

<form method="" action="" class="form">
    <div class="form-entry <?php echo array_key_exists('request-path', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <label for="">Redirect To</label>
        <select name="redirect-path" id="redirect-path">
            <option value=""> -- select redirect path</option>
            <option value="info">info</option>
            <option value="index">index</option>
        </select>
        <?php if ( array_key_exists('request-path', $_form_errors)): ?>
            <p class="form-error"><?php echo $_form_errors['request-path']; ?></p>
        <?php endif; ?>
        <select name="redirect-code" id="redirect-code">
            <option value="301">Moved Permanently (301)</option>
            <option value="302">Found (302)</option>
            <option value="303">See Other (303)</option>
            <option value="307">Temporary Redirect (307)</option>
            <option value="308">Permanent Redirect (308)</option>
        </select>
    </div>
    <button type="submit">
        <span class="">Submit</span>
    </button>
</form>
<pre><?php print_r($GLOBALS['.request_data']); ?></pre>


<?php ob_start(); ?>    
    <script>
        console.log('testing');
    </script>
<?php $GLOBALS['.html.script.inline'] = ob_get_clean(); ?>