<?php

  /**
   * 404 error page.
   * php version 8.0.0
   *
   * @author Bourg, Sean <sean.bourg@gmail.com>
   * @license https://opensource.org/licenses/GPL-3.0 GPL-v3
   */

  // Set up page.
  http_response_code(404);
  site_html_create(html_title: 'Page Not Found', page_title: 'Page Not Found');

  // Build original request query.
  $_request_uri = sprintf('%s://%s', $_SERVER['REQUEST_SCHEME'], $_SERVER['HTTP_HOST']);
  if ( !empty($_SERVER['REQUEST_URI']) ) {
    $_request_uri = sprintf('%s%s', $_request_uri, $_SERVER['REQUEST_URI']);
  }

  // Process get request.
  $_request = [];
  foreach ( $_GET as $_key => $_value ){
    if ( str_starts_with('_', $_key) ) {
      $_request[$_key] = $_value;
    }
  }  
  if ( !empty($_request) ) {
    $_request_uri = sprintf('%s?%s', $_request_uri, http_build_query($_request));
  }

  // Display html content.
?> 
<p>Sorry, but the page you were trying to view does not exist.</p>
<p>Request: <?php echo $_request_uri; ?></td>



