<?php

    /**
     * 500 error page.
     * php version 8.0.0
     *
     * @author Bourg, Sean <sean.bourg@gmail.com>
     * @license https://opensource.org/licenses/GPL-3.0 GPL-v3
     */

    http_response_code(500);
    site_html_create(html_title: 'Site Error', page_title: 'Site Error');

?>
<p>Site encountered an internal error.</p>
<?php if ( $GLOBALS['.request_data']['exception'] instanceof Throwable ): ?>
    <div id="ps-500-error">
        <pre><?php echo $GLOBALS['.request_data']['exception']->getMessage();?><ppre>
        <pre><?php echo $GLOBALS['.request_data']['exception']->getFile(); ?>:<?php echo $GLOBALS['.request_data']['exception']->getLine(); ?></pre>
    </div>
<?php endif; 
    