<?php
use function pirogue\database_collection_get;
use function pirogue\import;
use function pirogue\user_session_current;
use function site_access\site_user_require_access;

import('site_access');
import('pirogue\user_session');

$_user_session = user_session_current();
$_sqlsrv = database_collection_get();

site_user_require_access($_sqlsrv, $_user_session['id'], $GLOBALS['.pirogue.request.application'], 'user');
