<?php
    /**
     * Page master template.
     */
    
     $_user_session = pirogue_user_session_current();
    
?>
<!doctype html>
<html class="no-js" lang="">
    <head>
    <meta charset="utf-8">
    <title><?php echo $GLOBALS['.html.head.title'] ?? 'Test Page'; ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta name="theme-color" content="#fafafa">
    <link rel="manifest" href="site.webmanifest">
    <link rel="stylesheet" href="<?php echo pirogue_cdn_create_url('css/normalize.css', []); ?>">
    <link rel="stylesheet" href="<?php echo pirogue_cdn_create_url('css/style.css', []); ?>">
    <?php foreach ( $GLOBALS['.html.css.files'] ?? [] as $_file ): ?>
        <link rel="stylesheet" href="<?php echo pirogue_cdn_create_url("css/{$_file}.css", []); ?>.css">
    <?php endforeach; ?>
    <?php echo $GLOBALS['.html.css.inline'] ?? ''; ?>
    <?php echo $GLOBALS['.html.head'] ?? ''; ?>
    </head>
    <body id="<?php echo $GLOBALS['.html.body.id'] ?? ''; ?>" class="<?php echo $GLOBALS['.html.body.class'] ?? ''; ?>" class="clearfix">
        <header id="pageHeader">
            <h1 id="pageTitle"><a href="<?php echo $GLOBALS['.pirogue.dispatcher.address']; ?>">Test Site</a></h1>
            <h2 id="pageSubtitle"><?php echo $GLOBALS['.html.body.title']; ?></h2>
            <nav>
                <ul id="siteMenu">
                    <li><a href="<?php echo pirogue_dispatcher_create_url('info.html', []); ?>" title="" class=""><span class="">Info<span></a></li>
                    <li><a href="<?php echo pirogue_dispatcher_create_url('test.html', []); ?>" title="" class=""><span class="">Test<span></a></li>
                    <li><a href="<?php echo pirogue_dispatcher_create_url('user.html', []); ?>" title="" class=""><span class="">User<span></a></li>
                </ul>
                <div id="userMenu">
                    <?php if ( null == $_user_session ): ?>
                        <a href="<?php echo pirogue_dispatcher_create_url('login.html', []); ?>" title="" class=""><span class="">Login<span></a>
                    <?php else: ?>
                        <a href="<?php echo pirogue_dispatcher_create_url('logout.html', []); ?>" title="" class=""><span class="">Sign Out <?php echo $_user_session['username']; ?><span></a>
                    <?php endif; ?>
                </div>
            </nav>
        </header>
        <section id="pageBody">
            <?php $_site_notices = pirogue_site_notices_clear(); ?>
            <?php if ( !empty($_site_notices) ): ?>
                <?php foreach ( $_site_notices as $_notice): ?>
                    <p class="site-notice site-notice-<?php echo $_notice[0]; ?>"><?php echo $_notice[1]; ?></p>
                <?php endforeach; ?>
                <?php ob_start(); ?>
                    <script>
                        console.group('Site Notices');                        
                        <?php foreach ( $_site_notices as $_notice): ?>
                            console.log("type='<?php echo $_notice[0]; ?>', message='<?php echo $_notice[1]; ?>'");
                        <?php endforeach; ?>
                        console.groupEnd()
                    </script>
                <?php $GLOBALS['.html.script.inline'] .= ob_get_clean(); ?>
            <?php endif; ?>
            <?php echo $GLOBALS['.html.body.content'] ?? ''; ?>
        </section>
        <footer id="pageFooter"></footer>
        <script src="<?php echo pirogue_cdn_create_url('script/app.js', []); ?>"></script>
        <?php foreach ( $GLOBALS['.html.script.files'] ?? [] as $_file ): ?>
            <script src="script/<?php echo pirogue_cdn_create_url("script/{$_file}.js", []); ?>"></script>
        <?php endforeach; ?>
        <script>
            _pirogue_site_display(
                <?php echo json_encode($GLOBALS['.pirogue.dispatcher.address']); ?>,
                <?php echo json_encode($GLOBALS['.pirogue.dispatcher.request_path']); ?>,
                <?php echo json_encode($GLOBALS['.pirogue.dispatcher.request_data']); ?>,
            );
            console.log('request url: <?php echo json_encode(pirogue_dispatcher_create_url("{$GLOBALS['.pirogue.dispatcher.request_path']}.html", $GLOBALS['.pirogue.dispatcher.request_data'])); ?>');
            console.log('view: <?php echo json_encode($GLOBALS['._dispatcher_view']); ?>');
            console.log('request view: <?php echo json_encode($GLOBALS['._request_view']); ?>');
        </script>
        <?php echo $GLOBALS['.html.script.inline'] ?? ''; ?>
    </body>
</html>
