<?php

    $_form_errors = [];
    
    if ( null != pirogue_user_session_current() ) {
        return pirogue_dispatcher_redirect();
    }
    
    if ( 'POST' == $_SERVER['REQUEST_METHOD'] && 'login' == $_POST['action'] ?? '' ){
        // validate username.
        $_username = trim ( $_POST['login-email'] ?? '' ) ;
        if ( '' == $_username ){
            $_form_errors['login-email'] = 'Username is required.';
        }

        // validate password.
        $_password = trim ( $_POST['login-password'] ?? '' ) ;
        if ( '' == $_password ){
            $_form_errors['login-password'] = 'Password is required.';
        }

        // do login.
        if ( empty($_form_errors) ){
            $_database_connection = pirogue_database_collection_get();
            $_sql_result = mysqli_query(
                $_database_connection, 
                sprintf(
                    "SELECT id, username, email, IF(password=SHA2('%1\$s',256), 1, 0) AS is_valid
                        FROM users
                        WHERE (username='%2\$s' or email='%2\$s')
                        LIMIT 1",
                    mysqli_real_escape_string($_database_connection, $_password),
                    mysqli_real_escape_string($_database_connection, $_username),
                )
            );
            $_sql_data = mysqli_fetch_array($_sql_result, MYSQLI_ASSOC);
            mysqli_free_result($_sql_result);
            if ( null == $_sql_data ){
                $_form_errors['form'] = 'Invalid username.';
            } elseif ( 0 == $_sql_data['is_valid'] ) {
                $_form_errors['form'] = 'Invalid password.';
            } else {
                // success, store session and redirect.
                _pirogue_user_session_start([
                    'id' => $_sql_data['id'],
                    'username' => $_sql_data['username'],
                    'email' => $_sql_data['email'],
                ]);
                return pirogue_dispatcher_redirect();
            }
        } elseif ( !empty($_form_errors) ){
            $_form_errors['form'] = 'Login failed.';
        }
    }

    // Build page.
    site_html_create(html_title: 'Login', page_title: 'Login');

?>
<form id="" method="POST" action="<?php echo pirogue_dispatcher_create_url('login', []); ?>">
    <?php if ( array_key_exists('form', $_form_errors) ): ?>
        <p class="error-mesasage"><?php echo $_form_errors['form']; ?></p>
    <?php endif; ?>
    <div class="form-entry <?php echo array_key_exists('login-email', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <label for="">Email</label>
        <input type="text" id="" value="" name="login-email" placeholder="Enter account's email."/>
        <?php if ( array_key_exists('login-email', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['login-email']; ?></p>
        <?php endif; ?>
    </div>
    <div class="form-entry <?php echo array_key_exists('login-password', $_form_errors) ? 'form-entry-error' : ''; ?>">
        <label for="">Password</label>
        <input type="password" id="" value="" name="login-password" placeholder="Enter account's password."/>
        <?php if ( array_key_exists('login-password', $_form_errors) ): ?>
            <p class="error-mesasage"><?php echo $_form_errors['login-password']; ?></p>
        <?php endif; ?>
    </div>
    <div class="">
        <button name="action" type="submit" value="login"><span class="">Login</span></button>
    </div>
</form>