<?php 

    $_site_url = 'http://invlabsServer/example-site';
?>
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <title><?php echo $GLOBALS['.pirogue.html.head.title'] ?? ''; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
        <style>
        @font-face {
        	font-family: "Font Awesome 5 Brands";
        	font-style: normal;
        	font-weight: normal;
        	font-display: auto;
        	src: url(/assets/webfonts/font-awesome/fa-brands-400.eot);
        	src: url(/assets/webfonts/font-awesome/fa-brands-400.eot?#iefix)
        		format("embedded-opentype"),
        		url(/assets/webfonts/font-awesome/fa-brands-400.woff2) format("woff2"),
        		url(/assets/webfonts/font-awesome/fa-brands-400.woff) format("woff"),
        		url(/assets/webfonts/font-awesome/fa-brands-400.ttf) format("truetype"),
        		url(/assets/webfonts/font-awesome/fa-brands-400.svg#fontawesome)
        		format("svg") @font-face { font-family: "Font Awesome 5 Free";
        	font-style: normal;
        	font-weight: 400;
        	font-display: auto;
        	src: url(/assets/webfonts/font-awesome/fa-regular-400.eot);
        	src: url(/assets/webfonts/font-awesome/fa-regular-400.eot?#iefix)
        		format("embedded-opentype"),
        		url(/assets/webfonts/font-awesome/fa-regular-400.woff2) format("woff2"),
        		url(/assets/webfonts/font-awesome/fa-regular-400.woff) format("woff"),
        		url(/assets/webfonts/font-awesome/fa-regular-400.ttf) format("truetype"),
        		url(/assets/webfonts/font-awesome/fa-regular-400.svg#fontawesome)
        		format("svg")
        }
        
        @font-face {
        	font-family: "Font Awesome 5 Free";
        	font-style: normal;
        	font-weight: 900;
        	font-display: auto;
        	src: url(/assets/webfonts/font-awesome/fa-solid-900.eot);
        	src: url(/assets/webfonts/font-awesome/fa-solid-900.eot?#iefix)
        		format("embedded-opentype"),
        		url(/assets/webfonts/font-awesome/fa-solid-900.woff2) format("woff2"),
        		url(/assets/webfonts/font-awesome/fa-solid-900.woff) format("woff"),
        		url(/assets/webfonts/font-awesome/fa-solid-900.ttf) format("truetype"),
        		url(/assets/webfonts/font-awesome/fa-solid-900.svg#fontawesome) format("svg")
        }
        
        @font-face {
        	font-family: "Roboto";
        	font-style: normal;
        	font-weight: normal;
        	font-display: auto;
        	src: url(/assets/webfonts/roboto/Roboto-Regular.ttf) format("truetype");
        }
        
        @font-face {
        	font-family: "Roboto Slab";
        	font-style: normal;
        	font-weight: normal;
        	font-display: auto;
        	src: url(/assets/webfonts/roboto-slab/RobotoSlab-Regular.ttf)
        		format("truetype");
        }
        </style>
        <link rel="stylesheet" href="<?php echo $_site_url; ?>/assets/style/normalize.css">
        <link rel="stylesheet" href="<?php echo $_site_url; ?>/assets/style/page.css">
        <link rel="stylesheet" href="<?php echo $_site_url; ?>/assets/style/page-auth.css">
        <link rel="stylesheet" href="<?php echo $_site_url; ?>/assets/style/font-awesome.css">		
		<?php $_files = array_unique($GLOBALS['.pirogue.html.css.files'] ?? []);?>
      	<?php foreach( $_files as $_file ): ?>
      		<link rel="stylesheet" href="<?php echo $_site_url; ?>/style/<?php echo $_file; ?>.css" />
      	<?php endforeach; ?>
      	<?php echo $GLOBALS['.pirogue.html.css.inline'] ?? '' ?>
      	<meta name="theme-color" content="#fafafa">
      	<?php echo $GLOBALS['.pirogue.html.head']; ?>
	</head>
	<body id="<?php echo $GLOBALS['.pirogue.html.body.id'] ?? '' ?>" class="<?php echo $GLOBALS['.pirogue.html.body.class'] ?? '' ?>">
        <!--[if IE]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
		<div class="" id="page-content"><?php echo $GLOBALS['.pirogue.html.body.content'] ?? '' ?></div>
		<?php $_files = array_unique($GLOBALS['.pirogue.html.script.files'] ?? []);?>
      	<?php foreach( $_files as $_file ): ?>
      		<script src="<?php echo $_site_url; ?>/assets/script/<?php echo $_file; ?>.js"></script>
      	<?php endforeach; ?>
      	<?php echo $GLOBALS['.pirogue.html.script.inline'] ?? '' ?>
	</body>
</html>






