<?php
    use function pirogue\dispatcher_create_url;

    $GLOBALS['.html.body.title'] = 'Main Page';
?>
<menu>
    <li>
        <a href="<?php echo dispatcher_create_url("info", []); ?>" id="" class="">
            <span>Info</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("dispatcher", []); ?>" id="" class="">
            <span>Dispatcher</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("user-session", []); ?>" id="" class="">
            <span>User Session</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("cdn", []); ?>" id="" class="">
            <span>CDN</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("constants", []); ?>" id="" class="">
            <span>Constants</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("database-collection", []); ?>" id="" class="">
            <span>Database Collection</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("error-handler", []); ?>" id="" class="">
            <span>Error Handler</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("import", []); ?>" id="" class="">
            <span>Import</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("site-notices", []); ?>" id="" class="">
            <span>Site Notices</span>
        </a>1
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("view", []); ?>" id="" class="">
            <span>View</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("404", []); ?>" id="" class="">
            <span>404</span>
        </a>
    </li>
    <li>
        <a href="<?php echo dispatcher_create_url("500", []); ?>" id="" class="">
            <span>500</span>
        </a>
    </li>
</menu>