<?php

    $_database_connection = pirogue_database_collection_get();

    
    $_sql_filter = "";

    $_order_by_field = 'username';
    $_order_by_dir = 'ASC';
    $_sql_query = "SELECT id, username, email FROM users {$_sql_filter} ORDER BY {$_order_by_field} {$_order_by_dir}";
    $_sql_result = mysqli_query($_database_connection, $_sql_query);

    // create page.
    site_html_create(html_title: 'Users', page_title: 'Users');

?>
<div class="page-actions">
    <a href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/create.html', $GLOBALS['.request_module']), []); ?>"><span class="">New User</span></a>
</div>
<?php if ( 0 == mysqli_num_rows($_sql_result) ): ?>
    <p class="page-notice">No Results</p>
<?php else: ?>
    <table class="results-display">
        <colgroup style="width: 8ex;">
        <colgroup style="">
        <colgroup style="">
        <colgroup style="width: 12ex;">
        <colgroup style="width: 25ex;">
        <colgroup style="width: 12ex;">
        <colgroup style="width: 12ex;">
        <thead>
            <tr>
                <th class="align-center">id</th>
                <th>username</th>
                <th>email</th>
                <th colspan="4" class="align-center">actions</th>
            </tr>
        </thead>
        <tbody>
            <?php while ( $_sql_data = mysqli_fetch_assoc($_sql_result) ): ?>
                <tr class="results-display-entry">
                    <td class="align-center"><?php echo $_sql_data['id']; ?></td>
                    <td><?php echo $_sql_data['username']; ?></td>
                    <td><?php echo $_sql_data['email']; ?></td>
                    <td class="action align-center">
                        <a title="" class="" href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s/%d.html', $GLOBALS['.request_module'], 'delete', $_sql_data['id']), []); ?>"><span class="">delete</span></a>
                    </td>
                    <td class="action align-center">
                        <a title="" class="" href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s/%d.html', $GLOBALS['.request_module'], 'update-password', $_sql_data['id']), []); ?>"><span class="">update password</span></a>
                    </td>
                    <td class="action align-center">
                        <a title="" class="" href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s/%d.html', $GLOBALS['.request_module'], 'update-info', $_sql_data['id']), []); ?>"><span class="">edit</span></a>
                    </td>
                    <td class="action align-center">
                        <a title="" class="" href="<?php echo pirogue_dispatcher_create_url(sprintf('%s/%s/%d.html', $GLOBALS['.request_module'], 'view', $_sql_data['id']), []); ?>"><span class="">view</span></a>
                    </td>
                </tr>
            <?php endwhile; ?>
        <tbody>
    </table>
<?php endif; ?>
