<?php
    pirogue_import_load('site/users');
    $_id = array_shift($GLOBALS['.request_path']);

    // verify input.
    if ( '' == $_id ) {
        return pirogue_dispatcher_redirect(pirogue_dispatcher_create_url($GLOBALS['.request_module'],[]));
    } 
        
    $_user_info = site_user_fetch_by_id(pirogue_database_collection_get(), $_id);
    if ( null == $_user_info ){
        pirogue_site_notices_create('Error', 'Unable to find requested user.');
        return pirogue_dispatcher_redirect(pirogue_dispatcher_create_url($GLOBALS['.request_module'],[]));   
    }
    
    // build page.
    site_html_create(html_title: 'User Details', page_title: 'User Details');

?>
<div class="page-actions">
    <a class="link-back" href="<?php echo pirogue_dispatcher_create_url($GLOBALS['.request_module'], []); ?>"><span class="">Back to list</span></a>
</div>
<div class="details-display">
    <div class="details-display-entry">
        <label class="details-display-label">Id</label>
        <span class="details-display-value"><?php echo $_user_info['id']; ?></span>
    </div>
    <div class="details-display-entry">
        <label class="details-display-label">Email</label>
        <span class="details-display-value"><?php echo $_user_info['email']; ?></span>
    </div>
    <div class="details-display-entry">
        <label class="details-display-label">Username</label>
        <span class="details-display-value"><?php echo $_user_info['username']; ?></span>
    </div>
    <div class="details-display-entry">
        <label class="details-display-label">Password Hash</label>
        <span class="details-display-value"><?php echo $_user_info['password']; ?></span>
    </div>
</div>

